apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: pmguene-dev
  labels:
    app: serveur-bd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serveur-bd
  template:
    metadata:
      labels:
        app: serveur-bd
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root123"
            - name: MYSQL_DATABASE
              value: "appdb"
            - name: MYSQL_USER
              value: "appuser"
            - name: MYSQL_PASSWORD
              value: "password123"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
